### ISSUE TITLE
every day SIGSEGV

### ISSUE THREAD

**Issue by TrurlMcByte** [HatsuneMiku3939/ngx_upstream_resolveMK#3]
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000556561b928fd in ngx_http_upstream_resolveMK_handler (ctx=0x5565661e7060) at /usr/src/ngx_upstream_resolveMK/ngx_http_upstream_resolveMK.c:437

warning: Source file is more recent than executable.
437                     peer->socklen = ctx->srvs[i].addrs[0].socklen;
(gdb) bt
#0  0x0000556561b928fd in ngx_http_upstream_resolveMK_handler (ctx=0x5565661e7060) at /usr/src/ngx_upstream_resolveMK/ngx_http_upstream_resolveMK.c:437
#1  0x0000556561abcde6 in ngx_resolver_report_srv (ctx=<optimized out>, r=<optimized out>) at src/core/ngx_resolver.c:4330
#2  ngx_resolver_srv_names_handler (cctx=<optimized out>) at src/core/ngx_resolver.c:3068
#3  0x0000556561abb773 in ngx_resolver_process_a (ans=61, trunc=<optimized out>, nan=<optimized out>, qtype=<optimized out>, code=2, ident=<optimized out>, n=<optimized out>, buf=0x55656659c4e0 "", r=0x556562cfa100)
    at src/core/ngx_resolver.c:2111
#4  ngx_resolver_process_response (r=0x556562cfa100, buf=buf@entry=0x7ffefa44e970 "\266_\201\202", n=<optimized out>, tcp=tcp@entry=0) at src/core/ngx_resolver.c:1844
#5  0x0000556561abc804 in ngx_resolver_udp_read (rev=0x5565678adec0) at src/core/ngx_resolver.c:1585
#6  0x0000556561acab5c in ngx_epoll_process_events (cycle=<optimized out>, timer=<optimized out>, flags=<optimized out>) at src/event/modules/ngx_epoll_module.c:902
#7  0x0000556561ac1993 in ngx_process_events_and_timers (cycle=cycle@entry=0x556562cddaf0) at src/event/ngx_event.c:242
#8  0x0000556561ac8b24 in ngx_worker_process_cycle (cycle=cycle@entry=0x556562cddaf0, data=data@entry=0x0) at src/os/unix/ngx_process_cycle.c:749
#9  0x0000556561ac74d7 in ngx_spawn_process (cycle=cycle@entry=0x556562cddaf0, proc=0x556561ac8ab0 <ngx_worker_process_cycle>, data=0x0, name=0x556561b985df "worker process", respawn=respawn@entry=0)
    at src/os/unix/ngx_process.c:198
#10 0x0000556561ac9d97 in ngx_reap_children (cycle=0x556562cddaf0) at src/os/unix/ngx_process_cycle.c:621
#11 ngx_master_process_cycle (cycle=0x556562cddaf0) at src/os/unix/ngx_process_cycle.c:174
#12 0x0000556561aa1b61 in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:375
```

It's very critical issue, because it's put nginx into full freeze

**Comment by runningman84** [comment]
is this still a problem?

**Comment by TrurlMcByte** [comment]
I've stop use it, because issue #2 is critical for me

**Comment by runningman84** [comment]
Do you have an alternative?

**Comment by TrurlMcByte** [comment]
Kubernetes proxy+coredns. So this alternative "not for all"
